# Generated by Django 6.0.8 on 2026-09-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('date_fabrication', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
