from allauth.account.forms import LoginForm as AllauthLoginForm
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.utils.translation import gettext_lazy as _
from django import forms
from django.db import transaction

from .models import User
from partenaires.models import Client


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.AdminUserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """

    FIELD_CLASSES = (
        "block w-full rounded-lg border border-slate-300 bg-white px-4 py-3 text-slate-900 "
        "placeholder:text-slate-400 shadow-sm transition focus:border-primary focus:outline-none "
        "focus:ring-2 focus:ring-primary/30"
    )

    nom = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': FIELD_CLASSES, 'placeholder': 'Nom'}),
    )
    prenom = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': FIELD_CLASSES, 'placeholder': 'Prénom'}),
    )
    adresse = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': FIELD_CLASSES, 'placeholder': 'Adresse'}),
    )
    telephone = forms.CharField(
        max_length=20, required=False,
        widget=forms.TextInput(attrs={'class': FIELD_CLASSES, 'placeholder': 'Téléphone'}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # applique la même classe aux champs générés par allauth (username, email, password1, password2)
        for name, field in self.fields.items():
            if name not in ('nom', 'prenom', 'adresse', 'telephone'):
                field.widget.attrs.update({'class': self.FIELD_CLASSES})
                if name == 'email':
                    field.widget.attrs['placeholder'] = 'Email'
                elif name == 'username':
                    field.widget.attrs['placeholder'] = "Nom d'utilisateur"
                elif name == 'password1':
                    field.widget.attrs['placeholder'] = 'Mot de passe'
                elif name == 'password2':
                    field.widget.attrs['placeholder'] = 'Confirmer le mot de passe'

            if name in ('password1', 'password2'):
                field.help_text = ''

    @transaction.atomic
    def save(self, request):
        """Create a public account and its linked business client profile."""
        user = super().save(request)
        user.role = User.Role.CLIENT
        user.name = f"{self.cleaned_data['prenom']} {self.cleaned_data['nom']}"
        user.telephone = self.cleaned_data['telephone']
        user.save(update_fields=['role', 'name', 'telephone'])
        Client.objects.create(
            user=user,
            nom=self.cleaned_data['nom'],
            prenom=self.cleaned_data['prenom'],
            telephone=user.telephone,
            adresse=self.cleaned_data['adresse'],
        )
        return user



class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """


class LoginForm(AllauthLoginForm):
    """
    Form rendered on the login screen (account/login.html).
    Applies the project's Tailwind field styling to every field
    generated by allauth, without redefining the fields themselves.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        field_classes = (
            "block w-full appearance-none rounded-xl border-2 border-slate-200 bg-white/90 px-4 py-3.5 text-slate-900 "
            "placeholder:text-slate-400 shadow-sm transition duration-200 hover:border-primary/60 "
            "focus:border-primary focus:bg-white focus:outline-none focus:ring-4 focus:ring-primary/20"
        )
        for name, field in self.fields.items():
            if name == "remember":
                field.widget.attrs.update({
                    "class": (
                        "h-4 w-4 appearance-none rounded border border-slate-400 bg-white "
                        "checked:border-primary checked:bg-primary focus:outline-none focus:ring-2 focus:ring-primary"
                    )
                })
            else:
                field.widget.attrs.update({"class": field_classes})
                if name == "login":
                    field.widget.attrs["placeholder"] = "Adresse e-mail ou nom d'utilisateur"
                elif name == "password":
                    field.widget.attrs["placeholder"] = "Saisissez votre mot de passe"
